package ar.edu.unju.fi.apu.dominio.hibernate;
// Generated 07/06/2015 16:27:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EncabezadoFacturas generated by hbm2java
 */
public class EncabezadoFacturas  implements java.io.Serializable {


     private String codigo;
     private Date fecha;
     private String cliente;
     private Set facturaDetalleses = new HashSet(0);

    public EncabezadoFacturas() {
    }

	
    public EncabezadoFacturas(String codigo, Date fecha) {
        this.codigo = codigo;
        this.fecha = fecha;
    }
    public EncabezadoFacturas(String codigo, Date fecha, String cliente, Set facturaDetalleses) {
       this.codigo = codigo;
       this.fecha = fecha;
       this.cliente = cliente;
       this.facturaDetalleses = facturaDetalleses;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public Set getFacturaDetalleses() {
        return this.facturaDetalleses;
    }
    
    public void setFacturaDetalleses(Set facturaDetalleses) {
        this.facturaDetalleses = facturaDetalleses;
    }




}


