package ar.edu.unju.fi.apu.dominio.hibernate;
// Generated 07/06/2015 16:27:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturaDetalles generated by hbm2java
 */
public class FacturaDetalles  implements java.io.Serializable {


     private int codigo;
     private EncabezadoFacturas encabezadoFacturas;
     private Productos productos;
     private BigDecimal precioVenta;
     private int cantidad;

    public FacturaDetalles() {
    }

    public FacturaDetalles(int codigo, EncabezadoFacturas encabezadoFacturas, Productos productos, BigDecimal precioVenta, int cantidad) {
       this.codigo = codigo;
       this.encabezadoFacturas = encabezadoFacturas;
       this.productos = productos;
       this.precioVenta = precioVenta;
       this.cantidad = cantidad;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public EncabezadoFacturas getEncabezadoFacturas() {
        return this.encabezadoFacturas;
    }
    
    public void setEncabezadoFacturas(EncabezadoFacturas encabezadoFacturas) {
        this.encabezadoFacturas = encabezadoFacturas;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


