package ar.edu.unju.fi.apu.dominio.hibernate;
// Generated 07/06/2015 16:27:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int codigo;
     private TipoProducto tipoProducto;
     private String nombre;
     private BigDecimal precio;
     private int stock;
     private byte[] foto;
     private boolean estado;
     private Set facturaDetalleses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(int codigo, TipoProducto tipoProducto, String nombre, BigDecimal precio, int stock, byte[] foto, boolean estado) {
        this.codigo = codigo;
        this.tipoProducto = tipoProducto;
        this.nombre = nombre;
        this.precio = precio;
        this.stock = stock;
        this.foto = foto;
        this.estado = estado;
    }
    public Productos(int codigo, TipoProducto tipoProducto, String nombre, BigDecimal precio, int stock, byte[] foto, boolean estado, Set facturaDetalleses) {
       this.codigo = codigo;
       this.tipoProducto = tipoProducto;
       this.nombre = nombre;
       this.precio = precio;
       this.stock = stock;
       this.foto = foto;
       this.estado = estado;
       this.facturaDetalleses = facturaDetalleses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getFacturaDetalleses() {
        return this.facturaDetalleses;
    }
    
    public void setFacturaDetalleses(Set facturaDetalleses) {
        this.facturaDetalleses = facturaDetalleses;
    }




}


