package ar.edu.unju.fi.apu.dominio.hibernate;
// Generated 07/06/2015 16:27:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private boolean estado;
     private Set productoses = new HashSet(0);

    public TipoProducto() {
    }

	
    public TipoProducto(int codigo, String nombre, boolean estado) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.estado = estado;
    }
    public TipoProducto(int codigo, String nombre, boolean estado, Set productoses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.estado = estado;
       this.productoses = productoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


