package ar.edu.unju.fi.apu.dominio.hibernate;
// Generated 07/06/2015 16:27:13 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String nombreUsuario;
     private String password;
     private String nombreReal;

    public Usuarios() {
    }

    public Usuarios(String nombreUsuario, String password, String nombreReal) {
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.nombreReal = nombreReal;
    }
   
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombreReal() {
        return this.nombreReal;
    }
    
    public void setNombreReal(String nombreReal) {
        this.nombreReal = nombreReal;
    }




}


