package ar.edu.unju.fi.apu.modelo.dominio;
// Generated 08/06/2015 18:13:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.List;


/**
 * EncabezadoFactura generated by hbm2java
 */
public class EncabezadoFactura  implements java.io.Serializable {
    
     private String codigo;
     private Date fecha;
     private String cliente;
     private List<FacturaDetalle> listaDetalles;
     
    public EncabezadoFactura() {
    }

	
    public EncabezadoFactura(String codigo, Date fecha) {
        this.codigo = codigo;
        this.fecha = fecha;
    }
    public EncabezadoFactura(String codigo, Date fecha, String cliente) {
       this.codigo = codigo;
       this.fecha = fecha;
       this.cliente = cliente;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

    public List<FacturaDetalle> getListaDetalles() {
        return listaDetalles;
    }

    public void setListaDetalles(List<FacturaDetalle> listaDetalles) {
        this.listaDetalles = listaDetalles;
    }





}


