package ar.edu.unju.fi.apu.modelo.dominio;
// Generated 08/06/2015 18:13:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {
    
     private String codigo;
     private Date fecha;
     private String cliente;
     private Set<DetalleFactura> detalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(String codigo, Date fecha) {
        this.codigo = codigo;
        this.fecha = fecha;
    }
    public Factura(String codigo, Date fecha, String cliente) {
       this.codigo = codigo;
       this.fecha = fecha;
       this.cliente = cliente;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

     public Set<DetalleFactura> getDetalles() {
        return detalles;
    }

    public void setDetalles(Set<DetalleFactura> detalles) {
        this.detalles = detalles;
    }
     
}


